version: 2 

seeds: 
  - name: productsubcategory
    config: 
      schema: RAW
      column_types: 
        productsubcategoryid: integer
        productcategoryid: integer
        name: varchar
        modifieddate: timestamp
