version: 2

sources:
  - name: fivetran_database
    config:
      enabled: true
    description: 'The adventure works oltp database provided by Microsoft'
    database: fivetran_database  
    schema: azure_sql_db_saleslt  
    freshness:
      warn_after: {count: 5, period: day}
      error_after: {count: 30, period: day}
    loaded_at_field: _FIVETRAN_SYNCED
    tables:
      - name: product
      - name: productcategory
        description: 'Details about the product category.'
      - name: salesorderheader
        description: The order header details for sales.
      - name: salesorderdetail
        description: The order details for all sales.
  - name: adventurworks
    config:
      enabled: true
    description: 'The adventure works dw created in dbt'
    database: adventurworks  
    schema: curated  
    tables:
      - name: fct_salesorderdetail
        description: 'The fact table for all the sales with details.'